// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wookashi.FeatureSwitcher.Manager.Database;

#nullable disable

namespace Wookashi.FeatureSwitcher.Manager.Database.Migrations
{
    [DbContext(typeof(NodesDataContext))]
    [Migration("20260104213825_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Wookashi.FeatureSwitcher.Manager.Database.Entities.NodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Wookashi.FeatureSwitcher.Manager.Database.Entities.StateChangesHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("TEXT");

                    b.Property<long>("FlagId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("NewValue")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("OldValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StateChangesHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
