@Node_HostAddress = http://localhost:5216/api

@disabledFeatureName = testFeatureNameDisabled
@enabledFeatureName = testFeatureNameEnabled
@applicationName = testApplicationName
@environment = testEnvironment

POST {{Node_HostAddress}}/features/register HTTP/1.1
content-type: application/json

{
  "AppName": "{{applicationName}}",
  "Environment": "{{environment}}",
  "Features": [
    {
      "FeatureName": "{{enabledFeatureName}}",
      "InitialState": true
    },
    {
      "FeatureName": "{{disabledFeatureName}}",
      "InitialState": false
    }
  ]
}

###

GET {{Node_HostAddress}}/applications/{{applicationName}}/features/{{enabledFeatureName}}/state/
Accept: application/json

###

GET {{Node_HostAddress}}/applications/{{applicationName}}/features/{{disabledFeatureName}}/state/
Accept: application/json

###

GET {{Node_HostAddress}}/applications/
Accept: application/json

###

GET {{Node_HostAddress}}/application/{{applicationName}}/features
Accept: application/json

###