@Node_HostAddress = http://localhost:5216

@disabledFeatureName = testFnDsbed
@enabledFeatureName = testFnEnbled
@applicationName = AppName
@environment = testEnv

POST {{Node_HostAddress}}/applications HTTP/1.1
content-type: application/json

{
  "appName": "{{applicationName}}",
  "environment": "{{environment}}",
  "features": [
    {
      "featureName": "{{enabledFeatureName}}",
      "initialState": true
    },
    {
      "featureName": "{{disabledFeatureName}}",
      "initialState": false
    }
  ]
}

###

GET {{Node_HostAddress}}/applications/
Accept: application/json

###

GET {{Node_HostAddress}}/applications/{{applicationName}}/features
Accept: application/json

###

GET {{Node_HostAddress}}/applications/{{applicationName}}/features/{{disabledFeatureName}}/state/
Accept: application/json

###


GET {{Node_HostAddress}}/applications/{{applicationName}}/features/{{enabledFeatureName}}/state/
Accept: application/json

###
